insert into MOCK_DATA (title) values ('Massachusetts College of Art');
insert into MOCK_DATA (title) values ('Universidade Estadual do Ceará');
insert into MOCK_DATA (title) values ('Volgograd State Technical University');
insert into MOCK_DATA (title) values ('Centro Universitário de João Pessoa');
insert into MOCK_DATA (title) values ('St. Michael''s College');
insert into MOCK_DATA (title) values ('Universidad Autónoma de Occidente');
insert into MOCK_DATA (title) values ('National University of Samoa');
insert into MOCK_DATA (title) values ('College of St. Scholastica');
insert into MOCK_DATA (title) values ('Delta University');
insert into MOCK_DATA (title) values ('University Institute of Teacher Training "Suor Orsola Benincasa"');
insert into MOCK_DATA (title) values ('Mount Royal College');
insert into MOCK_DATA (title) values ('European International University');
insert into MOCK_DATA (title) values ('Dr. Bhim Rao Abdekar University');
insert into MOCK_DATA (title) values ('Manuel S. Enverga University Foundation');
insert into MOCK_DATA (title) values ('Qingdao University');
insert into MOCK_DATA (title) values ('Bradley University');
insert into MOCK_DATA (title) values ('University of the Thai Chamber of Commerce');
insert into MOCK_DATA (title) values ('South West University Yucai College');
insert into MOCK_DATA (title) values ('Gulf Medical University');
insert into MOCK_DATA (title) values ('Loyola University of Chicago');
insert into MOCK_DATA (title) values ('Western International University');
insert into MOCK_DATA (title) values ('University of Hyderabad');
insert into MOCK_DATA (title) values ('Spring Arbor College');
insert into MOCK_DATA (title) values ('Westmont College');
insert into MOCK_DATA (title) values ('University of Illinois');
insert into MOCK_DATA (title) values ('Singapore Management University');
insert into MOCK_DATA (title) values ('Nakhchivan Private University');
insert into MOCK_DATA (title) values ('Atilim University');
insert into MOCK_DATA (title) values ('Vellore Institute of Technology');
insert into MOCK_DATA (title) values ('University of Wamia and Masuria in Olsztyn');
insert into MOCK_DATA (title) values ('Islamic University of Gaza');
insert into MOCK_DATA (title) values ('Tohwa University');
insert into MOCK_DATA (title) values ('Engineering College of Copenhagen');
insert into MOCK_DATA (title) values ('The Art Institutes International Portland');
insert into MOCK_DATA (title) values ('Universidad Particular de Chiclayo');
insert into MOCK_DATA (title) values ('Technische Universität München');
insert into MOCK_DATA (title) values ('Technological University (Pathein)');
insert into MOCK_DATA (title) values ('Ecole Nationale de la Météorologie');
insert into MOCK_DATA (title) values ('State Pedagogical University in Kryvyi Rih');
insert into MOCK_DATA (title) values ('Chittagong University of Engineering and Technology');
insert into MOCK_DATA (title) values ('Université Robert Schuman (Strasbourg III)');
insert into MOCK_DATA (title) values ('West Bengal University of Technology');
insert into MOCK_DATA (title) values ('University of Adelaide');
insert into MOCK_DATA (title) values ('California Western School of Law');
insert into MOCK_DATA (title) values ('Haigazian University');
insert into MOCK_DATA (title) values ('Bucknell University');
insert into MOCK_DATA (title) values ('Igbinedion University');
insert into MOCK_DATA (title) values ('Universidad Industrial de Santander');
insert into MOCK_DATA (title) values ('St. Petersburg State Marine Technical University');
insert into MOCK_DATA (title) values ('Universidad Empresarial Siglio 21');
